name: Domain Guards
description: A GitHub Action to protect your repository by trigger actions based on domain structures throughout the repo
author: "Dallin Schiffman"

permissions:
  contents: read
  actions: read
  issues: write
  pull-requests: write

inputs:
  github_token:
    description: "GitHub token to authenticate API requests for actions."
    required: true
  pr_number:
    description: "The pull request number to analyze."
    required: true
    default: "${{ github.event.pull_request.number }}"

runs:
  using: composite
  steps:
    - name: Checkout .dg files only
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.github_token }}
        sparse-checkout: |
          **/*.dg
        sparse-checkout-cone-mode: false

    - name: Run Domain Guards
      id: run-domain-guards
      shell: bash
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_PR_NUMBER: ${{ inputs.pr_number }}
      run: node ${{ github.action_path }}/dist/index.js

    - name: Upload current matches
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.pr_number }}-domain-guards-matches
        path: ${{ steps.run-domain-guards.outputs.matches_path }}
        overwrite: true
