name: Domain Guards
description: A GitHub Action to protect your repository by trigger actions based on domain structures throughout the repo
author: "Dallin Schiffman"

permissions:
  contents: read
  issues: write
  pull-requests: write

inputs:
  github_token:
    description: "GitHub token to authenticate API requests for actions."
    required: true
  pr_number:
    description: "The pull request number to analyze."
    required: true
    default: "${{ github.event.pull_request.number }}"

runs:
  using: node20
  main: dist/src/index.js
